{
    'name': 'Mobile Service Management',
    'version': '1.0',
    'summary': 'Module for managing mobile service shop daily activities.',
    'description':'This module provides an all-in-one solution for mobile'
                  ' service centers, helping them efficiently manage operations'
                  ' while maintaining high levels of customer satisfaction.',
    'category': 'Industries',
    'author': 'BABA Ahmed et BENJAAFAR Ismail',
    'company': 'usms',
    'maintainer': '',
    'website': 'https://www.monsite.com',
    'depends': ['stock_account', 'mail', 'product', 'account' ,'sale'],
    'data': ['security/mobile_service_shop_security.xml',
             'security/ir.model.access.csv',
             'views/mobile_service_views.xml',
             'views/product_template_views.xml',
             'views/product_product_views.xml',
             'views/terms_and_condition_views.xml',
             'views/mobile_complaint_description_views.xml',
             'views/mobile_complaint_views.xml',
             'views/brand_models_views.xml',
             'views/mobile_brand_views.xml',
             'wizard/mobile_create_invoice_views.xml',
             'reports/mobile_service_email_template.xml',
             'reports/mobile_service_ticket.xml',
             'data/mobile_service_data.xml',
             'data/mobile_service_email_template.xml'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
